# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180417_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=2)),
                ('birthday', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('birthplace', models.CharField(max_length=100)),
                ('liveplace', models.CharField(max_length=100)),
                ('userDefault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserDefault')),
            ],
        ),
    ]
