# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 19, 44, 0, 648350)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(default='男', max_length=2),
        ),
    ]
