# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180424_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 20, 26, 12, 538166)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthplace',
            field=models.CharField(default='未填写', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='liveplace',
            field=models.CharField(default='未填写', max_length=100),
        ),
    ]
