# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180424_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefault',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 14, 35, 473102)),
        ),
    ]
