# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-02 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180501_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sysEndTime',
            field=models.DateTimeField(default='1990-01-01 12:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysStartTime',
            field=models.DateTimeField(default='1990-01-01 12:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='userEndTime',
            field=models.DateTimeField(default='1990-01-01 12:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='userStartTime',
            field=models.DateTimeField(default='1990-01-01 12:00:00'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default='1990-01-01 12:00:00'),
        ),
    ]
