# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 08:34
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180426_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='未填写描述', max_length=100)),
                ('useTimes', models.PositiveSmallIntegerField(default=0)),
                ('emergencyLevel', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('userDefault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDefault')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 34, 40, 937051)),
        ),
    ]
