# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sysEndTime',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 12, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysStartTime',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 12, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userEndTime',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 12, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userStartTime',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 12, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 12, 0, tzinfo=utc)),
        ),
    ]
