# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 08:58
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180426_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未填写标题', max_length=20)),
                ('description', models.TextField(default='未填写描述')),
                ('userLevel', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('userStartTime', models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 58, 52, 802093))),
                ('userEndTime', models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 58, 52, 802093))),
                ('length', models.PositiveIntegerField(default=0)),
                ('sysStartTime', models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 58, 52, 802093)))),
                ('sysEndTime', models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 58, 52, 802093)))),
                ('sysLevel', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('state', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='emergencyLevel',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 17, 58, 52, 801093)),
        ),
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='userDefault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDefault'),
        ),
    ]
