# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180426_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sysEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 18, 2, 24, 54176)),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 18, 2, 24, 54176)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 18, 2, 24, 54176)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 18, 2, 24, 54176)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 18, 2, 24, 52176)),
        ),
    ]
