# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180505_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
