# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_event_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
