# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 07:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180426_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='length',
            field=models.PositiveIntegerField(default=0, help_text='单位分钟'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveSmallIntegerField(default=0, help_text='该事务的状态<br>0:等待被安排 1:已安排 2:已取消 3:已完成', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 42, 21, 768423)),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysLevel',
            field=models.PositiveSmallIntegerField(default=0, help_text='系统根据该事件信息及用户日常习惯计算得到的紧急性 [0,99]', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 42, 21, 768423)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 42, 21, 768423)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userLevel',
            field=models.PositiveSmallIntegerField(default=0, help_text='用户描述的事件紧急性 [0,3]', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='userStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 42, 21, 768423)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 16, 42, 21, 768423)),
        ),
    ]
