# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 08:20
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180427_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('userDefault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDefault')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='sysEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 20, 42, 791034)),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysLevel',
            field=models.PositiveSmallIntegerField(default=0, help_text='系统根据该事件信息及用户日常习惯计算得到的紧急性<br>取值[0,99]', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 20, 42, 791034)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 20, 42, 791034)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userLevel',
            field=models.PositiveSmallIntegerField(default=0, help_text='用户描述的事件紧急性<br>取值[0,3]', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='userStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 20, 42, 791034)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 20, 42, 791034)),
        ),
    ]
