# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180427_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationLogs',
            new_name='OperationLog',
        ),
        migrations.AlterField(
            model_name='event',
            name='sysEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 49, 12, 167805)),
        ),
        migrations.AlterField(
            model_name='event',
            name='sysStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 49, 12, 167805)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userEndTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 49, 12, 167805)),
        ),
        migrations.AlterField(
            model_name='event',
            name='userStartTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 49, 12, 167805)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 17, 49, 12, 167805)),
        ),
    ]
